version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Build
          command: |
            bash ./build.sh

workflows:
  version: 2
  apply:
    jobs:
      - build
  nightly:
    jobs:
      - build
    triggers:
      - schedule:
          cron: "0 * * * *"
          filters:
            branches:
              only:
                - master
