version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Meetup
          command: |
            ./meetup.sh $CIRCLE_PROJECT_USERNAME $CIRCLE_PROJECT_REPONAME $GITHUB_TOKEN $MEETUP_TOKEN
      - run:
          name: Slack
          command: |
            ./slack.sh --token="${SLACK_TOKEN}" --channel="cli-group" \
                --emoji=":construction_worker:" --username="awskrug" \
                --title="${CIRCLE_PROJECT_REPONAME} updated" "\`$(cat ./target/MESSAGE | xargs)\`"

workflows:
  version: 2
  apply:
    jobs:
      - build
  nightly:
    jobs:
      - build
    triggers:
      - schedule:
          cron: "0 * * * *"
          filters:
            branches:
              only:
                - master
