version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Meetup
          command: ./meetup.sh $CIRCLE_PROJECT_USERNAME $CIRCLE_PROJECT_REPONAME $GITHUB_TOKEN

workflows:
  version: 2
  apply:
    jobs:
      - build
  nightly:
    jobs:
      - build
    triggers:
      - schedule:
          cron: "0 * * * *"
          filters:
            branches:
              only:
                - master
